name       : apr-util
version    : 1.5.4
release    : 1
source     :
    - http://mirror.netinch.com/pub/apache//apr/apr-util-1.5.4.tar.bz2 : a6cf327189ca0df2fb9d5633d7326c460fe2b61684745fd7963e79a6dd0dc82e
license    : Apache-2.0
summary    : apr-util provides a number of abstractions for Apache apr
description: |
    apr-util provides a number of abstractions for Apache apr
builddeps  :
    - pkgconfig(apr-1)
setup      : |
    %configure --with-apr=/usr
build      : |
    %make
install    : |
    %make_install
