name       : apr-util
version    : 1.6.1
release    : 10
source     :
    - http://mirror.netinch.com/pub/apache/apr/apr-util-1.6.1.tar.bz2 : d3e12f7b6ad12687572a3a39475545a072608f4ba03a6ce8a3778f607dd0035b
license    : Apache-2.0
component  : programming
summary    : apr-util provides a number of abstractions for Apache apr
description: |
    apr-util provides a number of abstractions for Apache apr
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(expat)
    - pkgconfig(libpq)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - db5-devel
    - gdbm-devel
    - openldap-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Prevent-broken-test-from-running.patch
    %configure \
        --with-apr=/usr \
        --with-berkeley-db=/usr \
        --with-crypto \
        --with-gdbm=/usr \
        --with-ldap \
        --with-nss=/usr \
        --with-openssl=/usr \
        --with-pgsql=/usr \
        --with-sqlite3=/usr \
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
