name       : apr-util
version    : 1.5.4
release    : 5
source     :
    - http://mirror.netinch.com/pub/apache//apr/apr-util-1.5.4.tar.bz2 : a6cf327189ca0df2fb9d5633d7326c460fe2b61684745fd7963e79a6dd0dc82e
license    : Apache-2.0
summary    : apr-util provides a number of abstractions for Apache apr
description: |
    apr-util provides a number of abstractions for Apache apr
builddeps  :
    - pkgconfig(apr-1)
    - pkgconfig(expat)
    - pkgconfig(libpq)
    - pkgconfig(nss)
    - pkgconfig(openssl)
    - pkgconfig(sqlite3)
    - db5-devel
    - gdbm-devel
setup      : |
    %configure \
        --with-apr=/usr \
        --with-berkeley-db=/usr \
        --with-crypto \
        --with-gdbm=/usr \
        --with-nss=/usr \
        --with-openssl=/usr \
        --with-pgsql=/usr \
        --with-sqlite3=/usr \
build      : |
    %make
install    : |
    %make_install
